### ISSUE TITLE
Local run fails

### ISSUE THREAD

**Issue by iAbadia** [ProjectMOA/noTeRayesCo#7]
Local run fails if no DB running in localhost. Got the following error:
```
iabadia@X550JF:~/git-repos/noTeRayesCo$ npm start

> noterayesco@1.0.0 start /home/iabadia/git-repos/noTeRayesCo
> node app.js

Server running on http://:::8080
error connecting: Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    --------------------
    at Protocol._enqueue (/home/iabadia/git-repos/noTeRayesCo/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/iabadia/git-repos/noTeRayesCo/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/home/iabadia/git-repos/noTeRayesCo/node_modules/mysql/lib/Connection.js:130:18)
    at Object.<anonymous> (/home/iabadia/git-repos/noTeRayesCo/app.js:14:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

```

**Comment by iAbadia** [comment]
Fixed. Prints error but keeps running.
